##Fun little trick to insert copied data into a YAML file without ruining the formatting: Before inserting any data, type 'set paste',then press enter. After that, press 'i' and insert your code with ctrl-v. The formatting will not be lost.#
#
#
#
#
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

